jQuery(document).ready(function($){var supportSVG={init:function(){$('img.svg').each(function(){var $img=jQuery(this);var imgID=$img.attr('id');var imgClass=$img.attr('class');var imgURL=$img.attr('src');var imgwidth=$img.attr('width');var imgheight=$img.attr('height');$.get(imgURL,function(data){var $svg=$(data).find('svg');if(typeof imgID!=='undefined'){$svg=$svg.attr('id',imgID)}
if(typeof imgClass!=='undefined'){$svg=$svg.attr('class',imgClass+' replaced-svg');$svg=$svg.attr({width:imgwidth,height:imgheight})}
$svg=$svg.removeAttr('xmlns:a');$img.replaceWith($svg)},'xml')})},};supportSVG.init();if(window.location.hash){scroll(0,0);setTimeout(function(){scroll(0,0)},1)}
if(window.location.hash){jQuery('html,body').stop().animate({scrollTop:jQuery(window.location.hash).offset().top-100},1500)}
jQuery('.appointment-sec .explore-box ul li a').click(function(){jQuery(this).parents('li').siblings().removeClass('active');jQuery(this).parents('li').addClass('active')})
jQuery('.rtl-slider').slick({slidesToShow:1,slidesToScroll:1,arrows:!0,asNavFor:'.rtl-slider-nav',prevArrow:".prev-tab-arrow",nextArrow:".next-tab-arrow",});jQuery('.rtl-slider-nav').slick({slidesToShow:3,slidesToScroll:1,vertical:!0,asNavFor:'.rtl-slider',centerMode:!1,focusOnSelect:!0,prevArrow:".thumb-prev",nextArrow:".thumb-next",responsive:[{breakpoint:768,settings:{vertical:!1,}},]});jQuery('#wrt_review').click(function(){jQuery(".write-a-review-popup").addClass('active-review-popup');jQuery(this).siblings().removeClass('active')
jQuery(this).addClass('active')})
jQuery('.close-popup').click(function(){jQuery(".write-a-review-popup").removeClass('active-review-popup')})
jQuery(function(){var galleryThumbs=new Swiper(".gallery-thumbs",{direction:"horizontal",slidesPerView:3,slidesPerColumn:1,spaceBetween:20,slideToClickedSlide:!1,speed:1000,autoResize:!0,freeMode:!0,loop:!0,loopFillGroupWithBlank:!0,keyboard:{enabled:!0},navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},breakpoints:{768:{slidesPerView:3,spaceBetween:20,watchOverflow:!0,watchSlidesVisibility:!0,watchSlidesProgress:!0,direction:'vertical',},}});var galleryTop=new Swiper(".gallery-top",{slidesPerView:1,watchOverflow:!0,watchSlidesVisibility:!0,watchSlidesProgress:!0,preventInteractionOnTransition:!0,keyboard:{enabled:!0},navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},thumbs:{swiper:galleryThumbs,},});galleryTop.on('slideChangeTransitionStart',function(){galleryThumbs.slideTo(galleryTop.activeIndex)});galleryThumbs.on('transitionStart',function(){galleryTop.slideTo(galleryThumbs.activeIndex)})});jQuery(function(){jQuery(".accordion-content:not(:first-of-type)").css("display","none");jQuery(".custom-accordion-title:first-of-type").addClass("open");jQuery(".page-template-template-landing-page .accordion-content").css("display","none");jQuery(".page-template-template-landing-page .custom-accordion-title:first-of-type").removeClass("open");jQuery(".custom-accordion-title").click(function(){jQuery(".open").not(this).removeClass("open").next().slideUp(300);jQuery(this).toggleClass("open").next().slideToggle(300)})});width=jQuery(window).width();jQuery(window).on('load resize',function(){var resizeWidth=jQuery(window).width();if(resizeWidth<=767){jQuery('.faq-sidebar').removeClass('slide-sidebar').addClass('tab-mobile-menu')}else{jQuery('.faq-sidebar').removeClass('tab-mobile-menu open-tab-mobile').addClass('slide-sidebar');jQuery('.faq-details').addClass('active-side-content')}});jQuery('.menu-link li a span').click(function(e){e.preventDefault();jQuery(this).parents('li').siblings('li').removeClass('open-menu');jQuery(this).parents('li').toggleClass('open-menu')})
jQuery('.faq-toggle').click(function(){var $this=$(this);if($this.parent().hasClass('tab-mobile-menu')){jQuery('.faq-sidebar').removeClass('slide-sidebar').addClass('open-tab-mobile')}else{jQuery('.faq-sidebar').removeClass('open-tab-mobile').addClass('slide-sidebar')}
jQuery('.faq-details').addClass('active-side-content')});$('body').on('click','.tab-mobile-menu .side-bar-heading, #tabs-nav',function(e){e.preventDefault();var $this=$(this);$this.parent().toggleClass('open-tab-mobile')});$("#tabs-nav li").click(function(){$(this).closest('.open-tab-mobile').removeClass('open-tab-mobile')});jQuery('.close-sidebar').click(function(){jQuery('.faq-sidebar').removeClass('slide-sidebar');jQuery('.faq-details').removeClass('active-side-content')})
jQuery(".accordion-faq > .accordion li:first-of-type .inner.add").addClass("show");jQuery(".accordion-faq > .accordion li:first-of-type .inner.add").css("display","block");jQuery(".accordion-faq > .accordion li:first-of-type .sub-accordion ul li .inner").removeClass("show");jQuery(".accordion-faq > .accordion li:first-of-type .sub-accordion ul li .inner").css("display","none");jQuery(window).on('load resize',function(){if(window.location.href.indexOf("tab_index")>-1){$('html, body').animate({scrollTop:$("#contact").offset().top},1000)}});jQuery('.toggle').click(function(e){jQuery('.sub-accordion ul li .toggle').click(function(){jQuery(this).parent("li").siblings().find(".inner").slideUp(350)})
jQuery('.accordion > li').click(function(){jQuery(this).siblings('li').removeClass('active-toggle');jQuery(this).addClass('active-toggle')})
jQuery('.accordion > li.active-toggle').click(function(){jQuery(this).removeClass('active-toggle')})
jQuery('.sub-accordion ul li').click(function(){jQuery(this).siblings('li').removeClass('active-sub-toggle');jQuery(this).addClass('active-sub-toggle')})
jQuery('.sub-accordion ul li.active-sub-toggle').click(function(){jQuery(this).removeClass('active-sub-toggle')})
var $this=jQuery(this);if($this.next().hasClass('show')){$this.next().removeClass('show');$this.next().slideUp(350)}else{$this.parent().parent().find('li .inner').removeClass('show');$this.parent().parent().find('li .inner').slideUp(350);$this.next().toggleClass('show');$this.next().slideToggle(350)}});if(!(jQuery('.mod-faq').hasClass('custom-active'))){jQuery('#tabs-nav li:first-child').addClass('active');jQuery('.tab-content').hide();jQuery('.tab-content:first').show()}
jQuery('#tabs-nav li').click(function(){var $this=jQuery(this);jQuery('#tabs-nav li').removeClass('active');jQuery(this).addClass('active');jQuery('.tab-content').hide();var activeTab=jQuery(this).find('a').attr('href');jQuery(activeTab).fadeIn();setTimeout(function(){jQuery('html, body').animate({scrollTop:jQuery('#tabs-content').offset().top-($this.closest('.faq-sidebar').hasClass('fixed')?30:80),})},300);return!1});jQuery(function(){jQuery(document).on('click','.reviews-content.limit .seemore-content',function(e){e.preventDefault();jQuery('.show').hide();jQuery('.limit').show();jQuery(this).parents('.desc').find('.show').css('display','block');jQuery(this).parents('.desc').find('.limit').css('display','none')});jQuery(document).on('click','.seemore',function(e){e.preventDefault();jQuery(this).parents('.element-item').siblings().removeClass('active-element');jQuery(this).parents('.element-item').toggleClass('active-element');jQuery(this).addClass('active');jQuery('.show').hide();jQuery('.limit').show();jQuery(this).parents('.element-item').find('.article.show').css('display','block');jQuery(this).parents('.element-item').find('.article.limit').css('display','none')})})
jQuery(function(){jQuery(document).on('click','.readmore',function(e){e.preventDefault();jQuery(this).parents('.slick-slide').siblings().removeClass('show-slide-item');jQuery(this).parents('.slick-slide').addClass('show-slide-item');jQuery('.show').hide();jQuery('.limit').show();jQuery(this).parents('.slick-slide.slick-active').find('.review-cont.show').css('display','block');jQuery(this).parents('.slick-slide.slick-active').find('.review-cont.limit').css('display','none')})})
jQuery("#tab-links a.btn").hover(function(){var value=jQuery(this).attr('data-src');jQuery(".hover-box img").attr("src",value)});jQuery('a.btn-gallery').on('click',function(e){e.preventDefault();var gallery=jQuery(this).attr('href');jQuery(gallery).magnificPopup({delegate:'a',type:'image',gallery:{enabled:!0}}).magnificPopup('open')});jQuery('a.extarnal-link').on('click',function(e){e.preventDefault();var gallery=jQuery(this).attr('href');jQuery(gallery).magnificPopup({delegate:'a',type:'image',gallery:{enabled:!0}}).magnificPopup('open')});jQuery('.slider-project').slick({infinite:!0,slidesToShow:2,slidesToScroll:1,autoplay:!1,autoplaySpeed:3000,arrows:!0,});jQuery('.review-slider').slick({infinite:!0,slidesToShow:1,slidesToScroll:1,autoplay:!1,autoplaySpeed:3000,arrows:!0,responsive:[{breakpoint:577,settings:{arrows:!0,}},]});jQuery('.review-box-slider').slick({infinite:!0,slidesToShow:3,slidesToScroll:1,autoplay:!0,autoplaySpeed:3000,arrows:!0,responsive:[{breakpoint:1200,settings:{slidesToShow:2}},{breakpoint:768,settings:{slidesToShow:1}}]});jQuery('.link-slider').slick({infinite:!0,slidesToShow:2,slidesToScroll:1,autoplay:!0,autoplaySpeed:3000,arrows:!0,responsive:[{breakpoint:401,settings:{slidesToShow:1}},]});jQuery('.process-slider').slick({infinite:!1,slidesToShow:3,slidesToScroll:1,autoplay:!1,arrows:!1,responsive:[{breakpoint:768,settings:{slidesToShow:1,centerMode:!0,centerPadding:'30px',}},]});jQuery('.grid-desc').slick({infinite:!0,slidesToShow:3,slidesToScroll:1,autoplay:!0,autoplaySpeed:3000,arrows:!0,responsive:[{breakpoint:901,settings:{slidesToShow:1,}},]});jQuery('.inn-full-img').slick({slidesToShow:1,slidesToScroll:1,fade:!1,asNavFor:'.mini-inner-slider',arrows:!0,enabled:!0});jQuery('.mini-inner-slider').slick({infinite:!0,slidesToShow:3,asNavFor:'.inn-full-img',dots:!1,focusOnSelect:!0,vertical:!0,arrows:!0,});jQuery('.cell-slider').slick({infinite:!0,slidesToShow:1,slidesToScroll:1,autoplaySpeed:2000,arrows:!0,prevArrow:'.prev-tab-arrow',nextArrow:'.next-tab-arrow'});(function(){jQuery('.req-btn').on('click',function(e){e.preventDefault();jQuery('.get-started-popup').fadeIn(200)});jQuery('.get-started-popup').on('click',function(event){if("lightbox"==event.target.className){jQuery('.get-started-popup').fadeOut(200)}});jQuery('.close-popup').on('click',function(){jQuery('.get-started-popup').fadeOut(200)})})(jQuery);jQuery('.mega-menu-btn').click(function(){jQuery('body').addClass('hidden-body')
jQuery('.mobile-menu').addClass('active-mobile-nav');jQuery('.full-navigation').addClass('active-nav');jQuery("html").addClass("scroll-hide")})
jQuery('.close-icon').click(function(){jQuery('body').removeClass('hidden-body')
jQuery('.full-navigation').removeClass('active-nav');jQuery("html").removeClass("scroll-hide")})
jQuery('.close-mobile-menu').click(function(){jQuery('body').removeClass('hidden-body')
jQuery("html").removeClass("scroll-hide");jQuery('.mobile-menu').removeClass('active-mobile-nav')})
jQuery("#hinsdale").hover(function(){jQuery(".feature-img .img-box .default-img").addClass("none");jQuery(".feature-img .img-box .hinsdale").addClass("block");jQuery(".feature-img .img-box .evanston").removeClass("block")})
jQuery("#evanston").hover(function(){jQuery(".feature-img .img-box .default-img").addClass("none");jQuery(".feature-img .img-box .evanston").addClass("block");jQuery(".feature-img .img-box .hinsdale").removeClass("block")})
jQuery("#evanston, #hinsdale").mouseleave(function(){jQuery(".feature-img .img-box .default-img").removeClass("none");jQuery(".feature-img .img-box .evanston").removeClass("block");jQuery(".feature-img .img-box .hinsdale").removeClass("block")})
jQuery(".menu-dropdown button").click(function(){jQuery(this).toggleClass('active-menu')
jQuery(this).parents('.menu-dropdown').toggleClass('active-dropdown')});jQuery(window).bind("load",function(){if(document.readyState==="complete"){setTimeout(function(){jQuery(".pre-loader").fadeOut(200)},500)}
AOS.init({once:!0,duration:1000,delay:0,})})
jQuery(".play-button").click(function(){jQuery(this).parents('.video-poster').fadeOut();var youTubeUrl=jQuery('iframe').attr('id');jQuery('iframe').attr('id','');jQuery('iframe').attr('id',youTubeUrl);jQuery(this).parents(".custom-video").children('iframe')[0].id+="?&autoplay=1";jQuery(this).parents('.custom-video').find('video')[0].play()});jQuery(window).on('load resize',function(){var containerwidth=jQuery('.container').width();var containerfullwidth=jQuery('body').width();var spacialcontainer=(containerfullwidth-containerwidth)/2;jQuery('.spacial-container.left-auto').css('margin-left',spacialcontainer+'px')})
jQuery(window).scroll(function(){if(jQuery(this).scrollTop()>50){jQuery("header").addClass("fixed-header")}else{jQuery("header").removeClass("fixed-header")}});jQuery(window).scroll(function(){if(jQuery(this).scrollTop()>800){jQuery(".design-feature .feature-content .desc a").addClass("sticky")}else{jQuery(".design-feature .feature-content .desc a").removeClass("sticky")}});var timeoutId;var $videoBgAspect=jQuery(".videobg-aspect");var $videoBgWidth=jQuery(".videobg-width");var videoAspect=$videoBgAspect.outerHeight()/$videoBgAspect.outerWidth();function videobgEnlarge(){windowAspect=(jQuery(window).height()/jQuery(window).width());if(windowAspect>videoAspect){$videoBgWidth.width((windowAspect/videoAspect)*100+'%')}else{$videoBgWidth.width(100+"%")}}
jQuery(window).resize(function(){clearTimeout(timeoutId);timeoutId=setTimeout(videobgEnlarge,100)});jQuery(function(){videobgEnlarge()});$('.copy-url').on('click',function(){var $temp=jQuery("<input>");jQuery("body").append($temp);var copiedLink=$(this).attr('data-value');$temp.val(copiedLink).select();document.execCommand("copy");$temp.remove();$(this).next('.selected-msg').show();var that=$(this);setTimeout(function(){that.next('.selected-msg').fadeOut()},1000)})
$(window).bind('scroll',function(){var sidebarHeight=$(window).height()-400;if($(window).scrollTop()>sidebarHeight){$('.faq-sidebar.tab-mobile-menu').addClass('fixed');jQuery('#tabs-content').css('margin-top','72px')}else{$('.faq-sidebar.tab-mobile-menu').removeClass('fixed')}});$('.recognition-feature .feature-content .text-box .desc .btn').on('click',function(){$(this).parent().find('ul.insert-li').addClass('list-toggled')});$(window).on('load resize orientationchange',function(){if($(window).width()<1200){$('body').addClass('mobile-version')}else{$('body').removeClass('mobile-version')}});$(document).on('click touch',".faq-detail-wrap .back-to-topic-block a",function(e){e.stopPropagation();if($('body').hasClass('mobile-version')){if($(this).parents('.faq-block-left').hasClass('block-toggled')){$(this).parents('.faq-block-left').delay(800).removeClass('block-toggled')}else{$(this).parents('.faq-block-left').delay(800).addClass('block-toggled')}}});$(document).on('mouseenter',".faq-detail-wrap .back-to-topic-block",function(){if(!$('body').hasClass('mobile-version')){if($(this).parents('.faq-block-left').hasClass('block-toggled')){$(this).parents('.faq-block-left').delay(800).removeClass('block-toggled')}else{$(this).parents('.faq-block-left').delay(800).addClass('block-toggled')}}})})